### ISSUE TITLE
Feedback on the course please

### ISSUE THREAD

**Issue by lohriialo** [Kulbear/applied-data-science-with-python-specialization#1]
I want to take this course on coursera and looking for reviews on the course. Your repo came up on google search, please allow me to ask this question as a github issue :wink: 

I've done other python courses and few other production ready project recently so I'd say I'm fairly confident in Python but not a Pro, what's your feedback and review on the course please?

**Comment by Kulbear** [comment]
I don't know you detailed background, but for the Python part, I think your foundation is solid enough to take this course. Due to my personal time arrangement (I'm doing my master study), I only completed the first course, under a 5-star rating system, I'd like to give a 4-4.5 stars.
It covers (let's say all) basic python libraries you need to know to start playing with data science projects, and also some statistics. But the cons are the topic got covered are fairly simple.

**Comment by lohriialo** [comment]
Thank you much!
